-- Seed data for the ref_* tables (GICS, ISO countries, ISDA equity taxonomy). Always runs after the schema migrations.
-- GICS (2018 structure, effective until 2023-03-17) from
-- docs/references/master-data/gics-classification: one row per sub-industry, lowest level first.
-- Re-runnable: clears its tables and every table that depends on them (children first) before inserting; run the later seed migrations again afterwards.
DELETE FROM sec_exception_queue;
DELETE FROM sec_listing;
DELETE FROM sec_instrument_swp_leg;
DELETE FROM sec_instrument_swp_contract;
DELETE FROM sec_instrument_fwd_contract;
DELETE FROM sec_instrument_opt_series;
DELETE FROM sec_instrument_fut_contract;
DELETE FROM sec_instrument_fnd;
DELETE FROM sec_instrument_fi_bond;
DELETE FROM sec_instrument_eq_warrant_right;
DELETE FROM sec_instrument_eq_spt;
DELETE FROM sec_identifier_xref;
DELETE FROM sec_instrument;
DELETE FROM sec_issuer;
DELETE FROM ref_venue;
DELETE FROM ref_isda_equity_taxonomy;
DELETE FROM ref_gics;
DELETE FROM ref_country;

INSERT INTO ref_gics (
    sub_industry_code, sub_industry_name, sub_industry_description,
    industry_code, industry_name, industry_group_code, industry_group_name,
    sector_code, sector_name) VALUES
    ('10101010', 'Oil & Gas Drilling', 'Drilling contractors or owners of drilling rigs that contract their services for drilling wells', '101010', 'Energy Equipment & Services', '1010', 'Energy', '10', 'Energy'),
    ('10101020', 'Oil & Gas Equipment & Services', 'Manufacturers of equipment, including drilling rigs and equipment, and providers of supplies and services to companies involved in the drilling, evaluation and completion of oil and gas wells.', '101010', 'Energy Equipment & Services', '1010', 'Energy', '10', 'Energy'),
    ('10102010', 'Integrated Oil & Gas', 'Integrated oil companies engaged in the exploration & production of oil and gas, as well as at least one other significant activity in either refining, marketing and transportation, or chemicals.', '101020', 'Oil, Gas & Consumable Fuels', '1010', 'Energy', '10', 'Energy'),
    ('10102020', 'Oil & Gas Exploration & Production', 'Companies engaged in the exploration and production of oil and gas not classified elsewhere.', '101020', 'Oil, Gas & Consumable Fuels', '1010', 'Energy', '10', 'Energy'),
    ('10102030', 'Oil & Gas Refining & Marketing', 'Companies engaged in the refining and marketing of oil, gas and/or refined products not classified in the Integrated Oil & Gas or Independent Power Producers & Energy Traders Sub-Industries.', '101020', 'Oil, Gas & Consumable Fuels', '1010', 'Energy', '10', 'Energy'),
    ('10102040', 'Oil & Gas Storage & Transportation', 'Companies engaged in the storage and/or transportation of oil, gas and/or refined products. Includes diversified midstream natural gas companies, oil and refined product pipelines, coal slurry pipelines and oil & gas shipping companies.', '101020', 'Oil, Gas & Consumable Fuels', '1010', 'Energy', '10', 'Energy'),
    ('10102050', 'Coal & Consumable Fuels', 'Companies primarily involved in the production and mining of coal, related products and other consumable fuels related to the generation of energy. Excludes companies primarily producing gases classified in the Industrial Gases sub-industry and companies primarily mining for metallurgical (coking) coal used for steel production.', '101020', 'Oil, Gas & Consumable Fuels', '1010', 'Energy', '10', 'Energy'),
    ('15101010', 'Commodity Chemicals', 'Companies that primarily produce industrial chemicals and basic chemicals. Including but not limited to plastics, synthetic fibers, films, commodity-based paints & pigments, explosives and petrochemicals. Excludes chemical companies classified in the Diversified Chemicals, Fertilizers & Agricultural Chemicals, Industrial Gases, or Specialty Chemicals Sub-Industries.', '151010', 'Chemicals', '1510', 'Materials', '15', 'Materials'),
    ('15101020', 'Diversified Chemicals', 'Manufacturers of a diversified range of chemical products not classified in the Industrial Gases, Commodity Chemicals, Specialty Chemicals or Fertilizers & Agricultural Chemicals Sub-Industries.', '151010', 'Chemicals', '1510', 'Materials', '15', 'Materials'),
    ('15101030', 'Fertilizers & Agricultural Chemicals', 'Producers of fertilizers, pesticides, potash or other agriculture-related chemicals not classified elsewhere.', '151010', 'Chemicals', '1510', 'Materials', '15', 'Materials'),
    ('15101040', 'Industrial Gases', 'Manufacturers of industrial gases.', '151010', 'Chemicals', '1510', 'Materials', '15', 'Materials'),
    ('15101050', 'Specialty Chemicals', 'Companies that primarily produce high value-added chemicals used in the manufacture of a wide variety of products, including but not limited to fine chemicals, additives, advanced polymers, adhesives, sealants and specialty paints, pigments and coatings.', '151010', 'Chemicals', '1510', 'Materials', '15', 'Materials'),
    ('15102010', 'Construction Materials', 'Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified in the Building Products Sub-Industry.', '151020', 'Construction Materials', '1510', 'Materials', '15', 'Materials'),
    ('15103010', 'Metal & Glass Containers', 'Manufacturers of metal, glass or plastic containers. Includes corks and caps.', '151030', 'Containers & Packaging', '1510', 'Materials', '15', 'Materials'),
    ('15103020', 'Paper Packaging', 'Manufacturers of paper and cardboard containers and packaging.', '151030', 'Containers & Packaging', '1510', 'Materials', '15', 'Materials'),
    ('15104010', 'Aluminum', 'Producers of aluminum and related products, including companies that mine or process bauxite and companies that recycle aluminum to produce finished or semi-finished products. Excludes companies that primarily produce aluminum building materials classified in the Building Products Sub-Industry.', '151040', 'Metals & Mining', '1510', 'Materials', '15', 'Materials'),
    ('15104020', 'Diversified Metals & Mining', 'Companies engaged in the diversified production or extraction of metals and minerals not classified elsewhere. Including, but not limited to, nonferrous metal mining (except bauxite), salt and borate mining, phosphate rock mining, and diversified mining operations. Excludes iron ore mining, classified in the Steel Sub-Industry, bauxite mining, classified in the Aluminum Sub-Industry, and coal mining, classified in either the Steel or Coal & Consumable Fuels Sub-Industries.', '151040', 'Metals & Mining', '1510', 'Materials', '15', 'Materials'),
    ('15104025', 'Copper', 'Companies involved primarily in copper ore mining.', '151040', 'Metals & Mining', '1510', 'Materials', '15', 'Materials'),
    ('15104030', 'Gold', 'Producers of gold and related products, including companies that mine or process gold and the South African finance houses which primarily invest in, but do not operate, gold mines.', '151040', 'Metals & Mining', '1510', 'Materials', '15', 'Materials'),
    ('15104040', 'Precious Metals & Minerals', 'Companies mining precious metals and minerals not classified in the Gold Sub-Industry. Includes companies primarily mining platinum.', '151040', 'Metals & Mining', '1510', 'Materials', '15', 'Materials'),
    ('15104045', 'Silver', 'Companies primarily mining silver. Excludes companies classified in the Gold or Precious Metals & Minerals Sub-Industries.', '151040', 'Metals & Mining', '1510', 'Materials', '15', 'Materials'),
    ('15104050', 'Steel', 'Producers of iron and steel and related products, including metallurgical (coking) coal mining used for steel production.', '151040', 'Metals & Mining', '1510', 'Materials', '15', 'Materials'),
    ('15105010', 'Forest Products', 'Manufacturers of timber and related wood products. Includes lumber for the building industry.', '151050', 'Paper & Forest Products', '1510', 'Materials', '15', 'Materials'),
    ('15105020', 'Paper Products', 'Manufacturers of all grades of paper. Excludes companies specializing in paper packaging classified in the Paper Packaging Sub-Industry.', '151050', 'Paper & Forest Products', '1510', 'Materials', '15', 'Materials'),
    ('20101010', 'Aerospace & Defense', 'Manufacturers of civil or military aerospace and defense equipment, parts or products. Includes defense electronics and space equipment.', '201010', 'Aerospace & Defense', '2010', 'Capital Goods', '20', 'Industrials'),
    ('20102010', 'Building Products', 'Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.', '201020', 'Building Products', '2010', 'Capital Goods', '20', 'Industrials'),
    ('20103010', 'Construction & Engineering', 'Companies engaged in primarily non-residential construction. Includes civil engineering companies and large-scale contractors. Excludes companies classified in the Homebuilding Sub-Industry.', '201030', 'Construction & Engineering', '2010', 'Capital Goods', '20', 'Industrials'),
    ('20104010', 'Electrical Components & Equipment', 'Companies that produce electric cables and wires, electrical components or equipment not classified in the Heavy Electrical Equipment Sub-Industry.', '201040', 'Electrical Equipment', '2010', 'Capital Goods', '20', 'Industrials'),
    ('20104020', 'Heavy Electrical Equipment', 'Manufacturers of power-generating equipment and other heavy electrical equipment, including power turbines, heavy electrical machinery intended for fixed-use and large electrical systems. Excludes cables and wires, classified in the Electrical Components & Equipment Sub-Industry.', '201040', 'Electrical Equipment', '2010', 'Capital Goods', '20', 'Industrials'),
    ('20105010', 'Industrial Conglomerates', 'Diversified industrial companies with business activities in three or more sectors, none of which contributes a majority of revenues. Stakes held are predominantly of a controlling nature and stake holders maintain an operational interest in the running of the subsidiaries.', '201050', 'Industrial Conglomerates', '2010', 'Capital Goods', '20', 'Industrials'),
    ('20106010', 'Construction Machinery & Heavy Trucks', 'Manufacturers of heavy duty trucks, rolling machinery, earth-moving and construction equipment, and manufacturers of related parts. Includes non-military shipbuilding.', '201060', 'Machinery', '2010', 'Capital Goods', '20', 'Industrials'),
    ('20106015', 'Agricultural & Farm Machinery', 'Companies manufacturing agricultural machinery, farm machinery, and their related parts. Includes machinery used for the production of crops and agricultural livestock, agricultural tractors, planting and fertilizing machinery, fertilizer and chemical application equipment, and grain dryers and blowers.', '201060', 'Machinery', '2010', 'Capital Goods', '20', 'Industrials'),
    ('20106020', 'Industrial Machinery', 'Manufacturers of industrial machinery and industrial components. Includes companies that manufacture presses, machine tools, compressors, pollution control equipment, elevators, escalators, insulators, pumps, roller bearings and other metal fabrications.', '201060', 'Machinery', '2010', 'Capital Goods', '20', 'Industrials'),
    ('20107010', 'Trading Companies & Distributors', 'Trading companies and other distributors of industrial equipment and products.', '201070', 'Trading Companies & Distributors', '2010', 'Capital Goods', '20', 'Industrials'),
    ('20201010', 'Commercial Printing', 'Companies providing commercial printing services. Includes printers primarily serving the media industry.', '202010', 'Commercial Services & Supplies', '2020', 'Commercial & Professional Services', '20', 'Industrials'),
    ('20201050', 'Environmental & Facilities Services', 'Companies providing environmental and facilities maintenance services. Includes waste management, facilities management and pollution control services. Excludes large-scale water treatment systems classified in the Water Utilities Sub-Industry.', '202010', 'Commercial Services & Supplies', '2020', 'Commercial & Professional Services', '20', 'Industrials'),
    ('20201060', 'Office Services & Supplies', 'Providers of office services and manufacturers of office supplies and equipment not classified elsewhere.', '202010', 'Commercial Services & Supplies', '2020', 'Commercial & Professional Services', '20', 'Industrials'),
    ('20201070', 'Diversified Support Services', 'Companies primarily providing labor oriented support services to businesses and governments. Includes commercial cleaning services, dining & catering services, equipment repair services, industrial maintenance services, industrial auctioneers, storage & warehousing, transaction services, uniform rental services, and other business support services.', '202010', 'Commercial Services & Supplies', '2020', 'Commercial & Professional Services', '20', 'Industrials'),
    ('20201080', 'Security & Alarm Services', 'Companies providing security and protection services to business and governments. Includes companies providing services such as correctional facilities, security & alarm services, armored transportation & guarding. Excludes companies providing security software classified under the Systems Software Sub-Industry and home security services classified under the Specialized Consumer Services Sub-Industry. Also excludes companies manufacturing security system equipment classified under the Electronic Equipment & Instruments Sub-Industry.', '202010', 'Commercial Services & Supplies', '2020', 'Commercial & Professional Services', '20', 'Industrials'),
    ('20202010', 'Human Resource & Employment Services', 'Companies providing business support services relating to human capital management. Includes employment agencies, employee training, payroll & benefit support services, retirement support services and temporary agencies.', '202020', 'Professional Services', '2020', 'Commercial & Professional Services', '20', 'Industrials'),
    ('20202020', 'Research & Consulting Services', 'Companies primarily providing research and consulting services to businesses and governments not classified elsewhere. Includes companies involved in management consulting services, architectural design, business information or scientific research, marketing, and testing & certification services. Excludes companies providing information technology consulting services classified in the IT Consulting & Other Services Sub-Industry.', '202020', 'Professional Services', '2020', 'Commercial & Professional Services', '20', 'Industrials'),
    ('20301010', 'Air Freight & Logistics', 'Companies providing air freight transportation, courier and logistics services, including package and mail delivery and customs agents. Excludes those companies classified in the Airlines, Marine or Trucking Sub-Industries.', '203010', 'Air Freight & Logistics', '2030', 'Transportation', '20', 'Industrials'),
    ('20302010', 'Airlines', 'Companies providing primarily passenger air transportation.', '203020', 'Airlines', '2030', 'Transportation', '20', 'Industrials'),
    ('20303010', 'Marine', 'Companies providing goods or passenger maritime transportation. Excludes cruise-ships classified in the Hotels, Resorts & Cruise Lines Sub-Industry.', '203030', 'Marine', '2030', 'Transportation', '20', 'Industrials'),
    ('20304010', 'Railroads', 'Companies providing primarily goods and passenger rail transportation.', '203040', 'Road & Rail', '2030', 'Transportation', '20', 'Industrials'),
    ('20304020', 'Trucking', 'Companies providing primarily goods and passenger land transportation. Includes vehicle rental and taxi companies.', '203040', 'Road & Rail', '2030', 'Transportation', '20', 'Industrials'),
    ('20305010', 'Airport Services', 'Operators of airports and companies providing related services.', '203050', 'Transportation Infrastructure', '2030', 'Transportation', '20', 'Industrials'),
    ('20305020', 'Highways & Railtracks', 'Owners and operators of roads, tunnels and railtracks.', '203050', 'Transportation Infrastructure', '2030', 'Transportation', '20', 'Industrials'),
    ('20305030', 'Marine Ports & Services', 'Owners and operators of marine ports and related services.', '203050', 'Transportation Infrastructure', '2030', 'Transportation', '20', 'Industrials'),
    ('25101010', 'Auto Parts & Equipment', 'Manufacturers of parts and accessories for automobiles and motorcycles. Excludes companies classified in the Tires & Rubber Sub-Industry.', '251010', 'Auto Components', '2510', 'Automobiles & Components', '25', 'Consumer Discretionary'),
    ('25101020', 'Tires & Rubber', 'Manufacturers of tires and rubber.', '251010', 'Auto Components', '2510', 'Automobiles & Components', '25', 'Consumer Discretionary'),
    ('25102010', 'Automobile Manufacturers', 'Companies that produce mainly passenger automobiles and light trucks. Excludes companies producing mainly motorcycles and three-wheelers classified in the Motorcycle Manufacturers Sub-Industry and heavy duty trucks classified in the Construction Machinery & Heavy Trucks Sub-Industry.', '251020', 'Automobiles', '2510', 'Automobiles & Components', '25', 'Consumer Discretionary'),
    ('25102020', 'Motorcycle Manufacturers', 'Companies that produce motorcycles, scooters or three-wheelers. Excludes bicycles classified in the Leisure Products Sub-Industry.', '251020', 'Automobiles', '2510', 'Automobiles & Components', '25', 'Consumer Discretionary'),
    ('25201010', 'Consumer Electronics', 'Manufacturers of consumer electronics products including TVs, home audio equipment, game consoles, digital cameras, and related products. Excludes personal home computer manufacturers classified in the Technology Hardware, Storage & Peripherals Sub-Industry, and electric household appliances classified in the Household Appliances Sub-Industry.', '252010', 'Household Durables', '2520', 'Consumer Durables & Apparel', '25', 'Consumer Discretionary'),
    ('25201020', 'Home Furnishings', 'Manufacturers of soft home furnishings or furniture, including upholstery, carpets and wall-coverings.', '252010', 'Household Durables', '2520', 'Consumer Durables & Apparel', '25', 'Consumer Discretionary'),
    ('25201030', 'Homebuilding', 'Residential construction companies. Includes manufacturers of prefabricated houses and semi-fixed manufactured homes.', '252010', 'Household Durables', '2520', 'Consumer Durables & Apparel', '25', 'Consumer Discretionary'),
    ('25201040', 'Household Appliances', 'Manufacturers of electric household appliances and related products. Includes manufacturers of power and hand tools, including garden improvement tools. Excludes TVs and other audio and video products classified in the Consumer Electronics Sub-Industry and personal computers classified in the Technology Hardware, Storage & Peripherals Sub-Industry.', '252010', 'Household Durables', '2520', 'Consumer Durables & Apparel', '25', 'Consumer Discretionary'),
    ('25201050', 'Housewares & Specialties', 'Manufacturers of durable household products, including cutlery, cookware, glassware, crystal, silverware, utensils, kitchenware and consumer specialties not classified elsewhere.', '252010', 'Household Durables', '2520', 'Consumer Durables & Apparel', '25', 'Consumer Discretionary'),
    ('25202010', 'Leisure Products', 'Manufacturers of leisure products and equipment including sports equipment, bicycles and toys.', '252020', 'Leisure Products', '2520', 'Consumer Durables & Apparel', '25', 'Consumer Discretionary'),
    ('25203010', 'Apparel, Accessories & Luxury Goods', 'Manufacturers of apparel, accessories & luxury goods. Includes companies primarily producing designer handbags, wallets, luggage, jewelry and watches. Excludes shoes classified in the Footwear Sub-Industry.', '252030', 'Textiles, Apparel & Luxury Goods', '2520', 'Consumer Durables & Apparel', '25', 'Consumer Discretionary'),
    ('25203020', 'Footwear', 'Manufacturers of footwear. Includes sport and leather shoes.', '252030', 'Textiles, Apparel & Luxury Goods', '2520', 'Consumer Durables & Apparel', '25', 'Consumer Discretionary'),
    ('25203030', 'Textiles', 'Manufacturers of textile and related products not classified in the Apparel, Accessories & Luxury Goods, Footwear or Home Furnishings Sub-Industries.', '252030', 'Textiles, Apparel & Luxury Goods', '2520', 'Consumer Durables & Apparel', '25', 'Consumer Discretionary'),
    ('25301010', 'Casinos & Gaming', 'Owners and operators of casinos and gaming facilities. Includes companies providing lottery and betting services.', '253010', 'Hotels, Restaurants & Leisure', '2530', 'Consumer Services', '25', 'Consumer Discretionary'),
    ('25301020', 'Hotels, Resorts & Cruise Lines', 'Owners and operators of hotels, resorts and cruise-ships. Includes travel agencies, tour operators and related services not classified elsewhere . Excludes casino-hotels classified in the Casinos & Gaming Sub-Industry.', '253010', 'Hotels, Restaurants & Leisure', '2530', 'Consumer Services', '25', 'Consumer Discretionary'),
    ('25301030', 'Leisure Facilities', 'Owners and operators of leisure facilities, including sport and fitness centers, stadiums, golf courses and amusement parks not classified in the Movies & Entertainment Sub-Industry.', '253010', 'Hotels, Restaurants & Leisure', '2530', 'Consumer Services', '25', 'Consumer Discretionary'),
    ('25301040', 'Restaurants', 'Owners and operators of restaurants, bars, pubs, fast-food or take-out facilities. Includes companies that provide food catering services.', '253010', 'Hotels, Restaurants & Leisure', '2530', 'Consumer Services', '25', 'Consumer Discretionary'),
    ('25302010', 'Education Services', 'Companies providing educational services, either on-line or through conventional teaching methods. Includes, private universities, correspondence teaching, providers of educational seminars, educational materials and technical education. Excludes companies providing employee education programs classified in the Human Resources & Employment Services Sub-Industry', '253020', 'Diversified Consumer Services', '2530', 'Consumer Services', '25', 'Consumer Discretionary'),
    ('25302020', 'Specialized Consumer Services', 'Companies providing consumer services not classified elsewhere. Includes residential services, home security, legal services, personal services, renovation & interior design services, consumer auctions and wedding & funeral services.', '253020', 'Diversified Consumer Services', '2530', 'Consumer Services', '25', 'Consumer Discretionary'),
    ('25501010', 'Distributors', 'Distributors and wholesalers of general merchandise not classified elsewhere. Includes vehicle distributors.', '255010', 'Distributors', '2550', 'Retailing', '25', 'Consumer Discretionary'),
    ('25502020', 'Internet & Direct Marketing Retail', 'Companies providing retail services primarily on the Internet, through mail order, and TV home shopping retailers. Also includes companies providing online marketplaces for consumer products and services.', '255020', 'Internet & Direct Marketing Retail', '2550', 'Retailing', '25', 'Consumer Discretionary'),
    ('25503010', 'Department Stores', 'Owners and operators of department stores.', '255030', 'Multiline Retail', '2550', 'Retailing', '25', 'Consumer Discretionary'),
    ('25503020', 'General Merchandise Stores', 'Owners and operators of stores offering diversified general merchandise. Excludes hypermarkets and large-scale super centers classified in the Hypermarkets & Super Centers Sub-Industry.', '255030', 'Multiline Retail', '2550', 'Retailing', '25', 'Consumer Discretionary'),
    ('25504010', 'Apparel Retail', 'Retailers specialized mainly in apparel and accessories.', '255040', 'Specialty Retail', '2550', 'Retailing', '25', 'Consumer Discretionary'),
    ('25504020', 'Computer & Electronics Retail', 'Owners and operators of consumer electronics, computers, video and related products retail stores.', '255040', 'Specialty Retail', '2550', 'Retailing', '25', 'Consumer Discretionary'),
    ('25504030', 'Home Improvement Retail', 'Owners and operators of home and garden improvement retail stores. Includes stores offering building materials and supplies.', '255040', 'Specialty Retail', '2550', 'Retailing', '25', 'Consumer Discretionary'),
    ('25504040', 'Specialty Stores', 'Owners and operators of specialty retail stores not classified elsewhere. Includes jewelry stores, toy stores, office supply stores, health & vision care stores, and book & entertainment stores.', '255040', 'Specialty Retail', '2550', 'Retailing', '25', 'Consumer Discretionary'),
    ('25504050', 'Automotive Retail', 'Owners and operators of stores specializing in automotive retail. Includes auto dealers, gas stations, and retailers of auto accessories, motorcycles & parts, automotive glass, and automotive equipment & parts.', '255040', 'Specialty Retail', '2550', 'Retailing', '25', 'Consumer Discretionary'),
    ('25504060', 'Homefurnishing Retail', 'Owners and operators of furniture and home furnishings retail stores. Includes residential furniture, homefurnishings, housewares, and interior design. Excludes home and garden improvement stores, classified in the Home Improvement Retail Sub-Industry.', '255040', 'Specialty Retail', '2550', 'Retailing', '25', 'Consumer Discretionary'),
    ('30101010', 'Drug Retail', 'Owners and operators of primarily drug retail stores and pharmacies.', '301010', 'Food & Staples Retailing', '3010', 'Food & Staples Retailing', '30', 'Consumer Staples'),
    ('30101020', 'Food Distributors', 'Distributors of food products to other companies and not directly to the consumer.', '301010', 'Food & Staples Retailing', '3010', 'Food & Staples Retailing', '30', 'Consumer Staples'),
    ('30101030', 'Food Retail', 'Owners and operators of primarily food retail stores.', '301010', 'Food & Staples Retailing', '3010', 'Food & Staples Retailing', '30', 'Consumer Staples'),
    ('30101040', 'Hypermarkets & Super Centers', 'Owners and operators of hypermarkets and super centers selling food and a wide-range of consumer staple products. Excludes Food and Drug Retailers classified in the Food Retail and Drug Retail Sub-Industries, respectively.', '301010', 'Food & Staples Retailing', '3010', 'Food & Staples Retailing', '30', 'Consumer Staples'),
    ('30201010', 'Brewers', 'Producers of beer and malt liquors. Includes breweries not classified in the Restaurants Sub-Industry.', '302010', 'Beverages', '3020', 'Food, Beverage & Tobacco', '30', 'Consumer Staples'),
    ('30201020', 'Distillers & Vintners', 'Distillers, vintners and producers of alcoholic beverages not classified in the Brewers Sub-Industry.', '302010', 'Beverages', '3020', 'Food, Beverage & Tobacco', '30', 'Consumer Staples'),
    ('30201030', 'Soft Drinks', 'Producers of non-alcoholic beverages including mineral waters. Excludes producers of milk classified in the Packaged Foods Sub-Industry.', '302010', 'Beverages', '3020', 'Food, Beverage & Tobacco', '30', 'Consumer Staples'),
    ('30202010', 'Agricultural Products', 'Producers of agricultural products. Includes crop growers, owners of plantations and companies that produce and process foods but do not package and market them. Excludes companies classified in the Forest Products Sub-Industry and those that package and market the food products classified in the Packaged Foods Sub-Industry.', '302020', 'Food Products', '3020', 'Food, Beverage & Tobacco', '30', 'Consumer Staples'),
    ('30202030', 'Packaged Foods & Meats', 'Producers of packaged foods including dairy products, fruit juices, meats, poultry, fish and pet foods.', '302020', 'Food Products', '3020', 'Food, Beverage & Tobacco', '30', 'Consumer Staples'),
    ('30203010', 'Tobacco', 'Manufacturers of cigarettes and other tobacco products.', '302030', 'Tobacco', '3020', 'Food, Beverage & Tobacco', '30', 'Consumer Staples'),
    ('30301010', 'Household Products', 'Producers of non-durable household products, including detergents, soaps, diapers and other tissue and household paper products not classified in the Paper Products Sub-Industry.', '303010', 'Household Products', '3030', 'Household & Personal Products', '30', 'Consumer Staples'),
    ('30302010', 'Personal Products', 'Manufacturers of personal and beauty care products, including cosmetics and perfumes.', '303020', 'Personal Products', '3030', 'Household & Personal Products', '30', 'Consumer Staples'),
    ('35101010', 'Health Care Equipment', 'Manufacturers of health care equipment and devices. Includes medical instruments, drug delivery systems, cardiovascular & orthopedic devices, and diagnostic equipment.', '351010', 'Health Care Equipment & Supplies', '3510', 'Health Care Equipment & Services', '35', 'Health Care'),
    ('35101020', 'Health Care Supplies', 'Manufacturers of health care supplies and medical products not classified elsewhere. Includes eye care products, hospital supplies, and safety needle & syringe devices.', '351010', 'Health Care Equipment & Supplies', '3510', 'Health Care Equipment & Services', '35', 'Health Care'),
    ('35102010', 'Health Care Distributors', 'Distributors and wholesalers of health care products not classified elsewhere.', '351020', 'Health Care Providers & Services', '3510', 'Health Care Equipment & Services', '35', 'Health Care'),
    ('35102015', 'Health Care Services', 'Providers of patient health care services not classified elsewhere. Includes dialysis centers, lab testing services, and pharmacy management services. Also includes companies providing business support services to health care providers, such as clerical support services, collection agency services, staffing services and outsourced sales & marketing services', '351020', 'Health Care Providers & Services', '3510', 'Health Care Equipment & Services', '35', 'Health Care'),
    ('35102020', 'Health Care Facilities', 'Owners and operators of health care facilities, including hospitals, nursing homes, rehabilitation centers and animal hospitals.', '351020', 'Health Care Providers & Services', '3510', 'Health Care Equipment & Services', '35', 'Health Care'),
    ('35102030', 'Managed Health Care', 'Owners and operators of Health Maintenance Organizations (HMOs) and other managed plans.', '351020', 'Health Care Providers & Services', '3510', 'Health Care Equipment & Services', '35', 'Health Care'),
    ('35103010', 'Health Care Technology', 'Companies providing information technology services primarily to health care providers. Includes companies providing application, systems and/or data processing software, internet-based tools, and IT consulting services to doctors, hospitals or businesses operating primarily in the Health Care Sector', '351030', 'Health Care Technology', '3510', 'Health Care Equipment & Services', '35', 'Health Care'),
    ('35201010', 'Biotechnology', 'Companies primarily engaged in the research, development, manufacturing and/or marketing of products based on genetic analysis and genetic engineering. Includes companies specializing in protein-based therapeutics to treat human diseases. Excludes companies manufacturing products using biotechnology but without a health care application.', '352010', 'Biotechnology', '3520', 'Pharmaceuticals, Biotechnology & Life Sciences', '35', 'Health Care'),
    ('35202010', 'Pharmaceuticals', 'Companies engaged in the research, development or production of pharmaceuticals. Includes veterinary drugs.', '352020', 'Pharmaceuticals', '3520', 'Pharmaceuticals, Biotechnology & Life Sciences', '35', 'Health Care'),
    ('35203010', 'Life Sciences Tools & Services', 'Companies enabling the drug discovery, development and production continuum by providing analytical tools, instruments, consumables & supplies, clinical trial services and contract research services. Includes firms primarily servicing the pharmaceutical and biotechnology industries.', '352030', 'Life Sciences Tools & Services', '3520', 'Pharmaceuticals, Biotechnology & Life Sciences', '35', 'Health Care'),
    ('40101010', 'Diversified Banks', 'Large, geographically diverse banks with a national footprint whose revenues are derived primarily from conventional banking operations, have significant business activity in retail banking and small and medium corporate lending, and provide a diverse range of financial services. Excludes banks classified in the Regional Banks and Thrifts & Mortgage Finance Sub-Industries. Also excludes investment banks classified in the Investment Banking & Brokerage Sub-Industry.', '401010', 'Banks', '4010', 'Banks', '40', 'Financials'),
    ('40101015', 'Regional Banks', 'Commercial banks whose businesses are derived primarily from conventional banking operations and have significant business activity in retail banking and small and medium corporate lending. Regional banks tend to operate in limited geographic regions. Excludes companies classified in the Diversified Banks and Thrifts & Mortgage Banks sub-industries. Also excludes investment banks classified in the Investment Banking & Brokerage Sub-Industry.', '401010', 'Banks', '4010', 'Banks', '40', 'Financials'),
    ('40102010', 'Thrifts & Mortgage Finance', 'Financial institutions providing mortgage and mortgage related services. These include financial institutions whose assets are primarily mortgage related, savings & loans, mortgage lending institutions, building societies and companies providing insurance to mortgage banks.', '401020', 'Thrifts & Mortgage Finance', '4010', 'Banks', '40', 'Financials'),
    ('40201020', 'Other Diversified Financial Services', 'Providers of a diverse range of financial services and/or with some interest in a wide range of financial services including banking, insurance and capital markets, but with no dominant business line. Excludes companies classified in the Regional Banks and Diversified Banks Sub-Industries.', '402010', 'Diversified Financial Services', '4020', 'Diversified Financials', '40', 'Financials'),
    ('40201030', 'Multi-Sector Holdings', 'A company with significantly diversified holdings across three or more sectors, none of which contributes a majority of profit and/or sales. Stakes held are predominantly of a non-controlling nature. Includes diversified financial companies where stakes held are of a controlling nature. Excludes other diversified companies classified in the Industrials Conglomerates Sub-Industry.', '402010', 'Diversified Financial Services', '4020', 'Diversified Financials', '40', 'Financials'),
    ('40201040', 'Specialized Finance', 'Providers of specialized financial services not classified elsewhere. Companies in this sub-industry derive a majority of revenue from one specialized line of business. Includes, but not limited to, commercial financing companies, central banks, leasing institutions, factoring services, and specialty boutiques. Excludes companies classified in the Financial Exchanges & Data sub-industry.', '402010', 'Diversified Financial Services', '4020', 'Diversified Financials', '40', 'Financials'),
    ('40202010', 'Consumer Finance', 'Providers of consumer finance services, including personal credit, credit cards, lease financing, travel-related money services and pawn shops. Excludes mortgage lenders classified in the Thrifts & Mortgage Finance Sub-Industry.', '402020', 'Consumer Finance', '4020', 'Diversified Financials', '40', 'Financials'),
    ('40203010', 'Asset Management & Custody Banks', 'Financial institutions primarily engaged in investment management and/or related custody and securities fee-based services. Includes companies operating mutual funds, closed-end funds and unit investment trusts. Excludes banks and other financial institutions primarily involved in commercial lending, investment banking, brokerage and other specialized financial activities.', '402030', 'Capital Markets', '4020', 'Diversified Financials', '40', 'Financials'),
    ('40203020', 'Investment Banking & Brokerage', 'Financial institutions primarily engaged in investment banking & brokerage services, including equity and debt underwriting, mergers and acquisitions, securities lending and advisory services. Excludes banks and other financial institutions primarily involved in commercial lending, asset management and specialized financial activities.', '402030', 'Capital Markets', '4020', 'Diversified Financials', '40', 'Financials'),
    ('40203030', 'Diversified Capital Markets', 'Financial institutions primarily engaged in diversified capital markets activities, including a significant presence in at least two of the following area: large/major corporate lending, investment banking, brokerage and asset management. Excludes less diversified companies classified in the Asset Management & Custody Banks or Investment Banking & Brokerage sub-industries. Also excludes companies classified in the Banks or Insurance industry groups or the Consumer Finance Sub-Industry.', '402030', 'Capital Markets', '4020', 'Diversified Financials', '40', 'Financials'),
    ('40203040', 'Financial Exchanges & Data', 'Financial exchanges for securities, commodities, derivatives and other financial instruments, and providers of financial decision support tools and products including ratings agencies', '402030', 'Capital Markets', '4020', 'Diversified Financials', '40', 'Financials'),
    ('40204010', 'Mortgage REITs', 'Companies or Trusts that service, originate, purchase and/or securitize residential and/or commercial mortgage loans. Includes trusts that invest in mortgage-backed securities and other mortgage related assets.', '402040', 'Mortgage Real Estate Investment Trusts (REITs)', '4020', 'Diversified Financials', '40', 'Financials'),
    ('40301010', 'Insurance Brokers', 'Insurance and reinsurance brokerage firms.', '403010', 'Insurance', '4030', 'Insurance', '40', 'Financials'),
    ('40301020', 'Life & Health Insurance', 'Companies providing primarily life, disability, indemnity or supplemental health insurance. Excludes managed care companies classified in the Managed Health Care Sub-Industry.', '403010', 'Insurance', '4030', 'Insurance', '40', 'Financials'),
    ('40301030', 'Multi-line Insurance', 'Insurance companies with diversified interests in life, health and property and casualty insurance.', '403010', 'Insurance', '4030', 'Insurance', '40', 'Financials'),
    ('40301040', 'Property & Casualty Insurance', 'Companies providing primarily property and casualty insurance.', '403010', 'Insurance', '4030', 'Insurance', '40', 'Financials'),
    ('40301050', 'Reinsurance', 'Companies providing primarily reinsurance.', '403010', 'Insurance', '4030', 'Insurance', '40', 'Financials'),
    ('45102010', 'IT Consulting & Other Services', 'Providers of information technology and systems integration services not classified in the Data Processing & Outsourced Services Sub-Industry. Includes information technology consulting and information management services.', '451020', 'IT Services', '4510', 'Software & Services', '45', 'Information Technology'),
    ('45102020', 'Data Processing & Outsourced Services', 'Providers of commercial electronic data processing and/or business process outsourcing services. Includes companies that provide services for back-office automation.', '451020', 'IT Services', '4510', 'Software & Services', '45', 'Information Technology'),
    ('45102030', 'Internet Services & Infrastructure', 'Companies providing services and infrastructure for the internet industry including data centers and cloud networking and storage infrastructure. Also includes companies providing web hosting services. Excludes companies classified in the Software Industry.', '451020', 'IT Services', '4510', 'Software & Services', '45', 'Information Technology'),
    ('45103010', 'Application Software', 'Companies engaged in developing and producing software designed for specialized applications for the business or consumer market. Includes enterprise and technical software, as well as cloud-based software. Excludes companies classified in the Interactive Home Entertainment Sub-Industry. Also excludes companies producing systems or database management software classified in the Systems Software Sub-Industry.', '451030', 'Software', '4510', 'Software & Services', '45', 'Information Technology'),
    ('45103020', 'Systems Software', 'Companies engaged in developing and producing systems and database management software.', '451030', 'Software', '4510', 'Software & Services', '45', 'Information Technology'),
    ('45201020', 'Communications Equipment', 'Manufacturers of communication equipment and products, including LANs, WANs, routers, telephones, switchboards and exchanges. Excludes cellular phone manufacturers classified in the Technology Hardware, Storage & Peripherals Sub-Industry.', '452010', 'Communications Equipment', '4520', 'Technology Hardware & Equipment', '45', 'Information Technology'),
    ('45202030', 'Technology Hardware, Storage & Peripherals', 'Manufacturers of cellular phones, personal computers, servers, electronic computer components and peripherals. Includes data storage components, motherboards, audio and video cards, monitors, keyboards, printers, and other peripherals. Excludes semiconductors classified in the Semiconductors Sub-Industry.', '452020', 'Technology Hardware, Storage & Peripherals', '4520', 'Technology Hardware & Equipment', '45', 'Information Technology'),
    ('45203010', 'Electronic Equipment & Instruments', 'Manufacturers of electronic equipment and instruments including analytical, electronic test and measurement instruments, scanner/barcode products, lasers, display screens, point-of-sales machines, and security system equipment.', '452030', 'Electronic Equipment, Instruments & Components', '4520', 'Technology Hardware & Equipment', '45', 'Information Technology'),
    ('45203015', 'Electronic Components', 'Manufacturers of electronic components. Includes electronic components, connection devices, electron tubes, electronic capacitors and resistors, electronic coil, printed circuit board, transformer and other inductors, signal processing technology/components.', '452030', 'Electronic Equipment, Instruments & Components', '4520', 'Technology Hardware & Equipment', '45', 'Information Technology'),
    ('45203020', 'Electronic Manufacturing Services', 'Producers of electronic equipment mainly for the OEM (Original Equipment Manufacturers) markets.', '452030', 'Electronic Equipment, Instruments & Components', '4520', 'Technology Hardware & Equipment', '45', 'Information Technology'),
    ('45203030', 'Technology Distributors', 'Distributors of technology hardware and equipment. Includes distributors of communications equipment, computers & peripherals, semiconductors, and electronic equipment and components.', '452030', 'Electronic Equipment, Instruments & Components', '4520', 'Technology Hardware & Equipment', '45', 'Information Technology'),
    ('45301010', 'Semiconductor Equipment', 'Manufacturers of semiconductor equipment, including manufacturers of the raw material and equipment used in the solar power industry.', '453010', 'Semiconductors & Semiconductor Equipment', '4530', 'Semiconductors & Semiconductor Equipment', '45', 'Information Technology'),
    ('45301020', 'Semiconductors', 'Manufacturers of semiconductors and related products, including manufacturers of solar modules and cells.', '453010', 'Semiconductors & Semiconductor Equipment', '4530', 'Semiconductors & Semiconductor Equipment', '45', 'Information Technology'),
    ('50101010', 'Alternative Carriers', 'Providers of communications and high-density data transmission services primarily through a high bandwidth/fiber-optic cable network.', '501010', 'Diversified Telecommunication Services', '5010', 'Telecommunication Services', '50', 'Communication Services'),
    ('50101020', 'Integrated Telecommunication Services', 'Operators of primarily fixed-line telecommunications networks and companies providing both wireless and fixed-line telecommunications services not classified elsewhere. Also includes internet service providers offering internet access to end users.', '501010', 'Diversified Telecommunication Services', '5010', 'Telecommunication Services', '50', 'Communication Services'),
    ('50102010', 'Wireless Telecommunication Services', 'Providers of primarily cellular or wireless telecommunication services.', '501020', 'Wireless Telecommunication Services', '5010', 'Telecommunication Services', '50', 'Communication Services'),
    ('50201010', 'Advertising', 'Companies providing advertising, marketing or public relations services.', '502010', 'Media', '5020', 'Media & Entertainment', '50', 'Communication Services'),
    ('50201020', 'Broadcasting', 'Owners and operators of television or radio broadcasting systems, including programming. Includes radio and television broadcasting, radio networks, and radio stations.', '502010', 'Media', '5020', 'Media & Entertainment', '50', 'Communication Services'),
    ('50201030', 'Cable & Satellite', 'Providers of cable or satellite television services. Includes cable networks and program distribution.', '502010', 'Media', '5020', 'Media & Entertainment', '50', 'Communication Services'),
    ('50201040', 'Publishing', 'Publishers of newspapers, magazines and books in print or electronic formats.', '502010', 'Media', '5020', 'Media & Entertainment', '50', 'Communication Services'),
    ('50202010', 'Movies & Entertainment', 'Companies that engage in producing and selling entertainment products and services, including companies engaged in the production, distribution and screening of movies and television shows, producers and distributors of music, entertainment theaters and sports teams. Also includes companies offering and/or producing entertainment content streamed online.', '502020', 'Entertainment', '5020', 'Media & Entertainment', '50', 'Communication Services'),
    ('50202020', 'Interactive Home Entertainment', 'Producers of interactive gaming products, including mobile gaming applications. Also includes educational software used primarily in the home. Excludes online gambling companies classified in the Casinos & Gaming Sub-Industry.', '502020', 'Entertainment', '5020', 'Media & Entertainment', '50', 'Communication Services'),
    ('50203010', 'Interactive Media & Services', 'Companies engaging in content and information creation or distribution through proprietary platforms, where revenues are derived primarily through pay-per-click advertisements. Includes search engines, social media and networking platforms, online classifieds, and online review companies. Excludes companies operating online marketplaces classified in Internet & Direct Marketing Retail.', '502030', 'Interactive Media & Services', '5020', 'Media & Entertainment', '50', 'Communication Services'),
    ('55101010', 'Electric Utilities', 'Companies that produce or distribute electricity. Includes both nuclear and non-nuclear facilities.', '551010', 'Electric Utilities', '5510', 'Utilities', '55', 'Utilities'),
    ('55102010', 'Gas Utilities', 'Companies whose main charter is to distribute and transmit natural and manufactured gas. Excludes companies primarily involved in gas exploration or production classified in the Oil & Gas Exploration & Production Sub-Industry. Also excludes companies engaged in the storage and/or transportation of oil, gas, and/or refined products classified in the Oil & Gas Storage & Transportation Sub-Industry.', '551020', 'Gas Utilities', '5510', 'Utilities', '55', 'Utilities'),
    ('55103010', 'Multi-Utilities', 'Utility companies with significantly diversified activities in addition to core Electric Utility, Gas Utility and/or Water Utility operations.', '551030', 'Multi-Utilities', '5510', 'Utilities', '55', 'Utilities'),
    ('55104010', 'Water Utilities', 'Companies that purchase and redistribute water to the end-consumer. Includes large-scale water treatment systems.', '551040', 'Water Utilities', '5510', 'Utilities', '55', 'Utilities'),
    ('55105010', 'Independent Power Producers & Energy Traders', 'Companies that operate as Independent Power Producers (IPPs), Gas & Power Marketing & Trading Specialists and/or Integrated Energy Merchants. Excludes producers of electricity using renewable sources, such as solar power, hydropower, and wind power. Also excludes electric transmission companies and utility distribution companies classified in the Electric Utilities Sub-Industry.', '551050', 'Independent Power and Renewable Electricity Producers', '5510', 'Utilities', '55', 'Utilities'),
    ('55105020', 'Renewable Electricity', 'Companies that engage in the generation and distribution of electricity using renewable sources, including, but not limited to, companies that produce electricity using biomass, geothermal energy, solar energy, hydropower, and wind power. Excludes companies manufacturing capital equipment used to generate electricity using renewable sources, such as manufacturers of solar power systems, installers of photovoltaic cells, and companies involved in the provision of technology, components, and services mainly to this market.', '551050', 'Independent Power and Renewable Electricity Producers', '5510', 'Utilities', '55', 'Utilities'),
    ('60101010', 'Diversified REITs', 'A company or Trust with significantly diversified operations across two or more property types.', '601010', 'Equity Real Estate Investment Trusts (REITs)', '6010', 'Real Estate', '60', 'Real Estate'),
    ('60101020', 'Industrial REITs', 'Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of industrial properties. Includes companies operating industrial warehouses and distribution properties.', '601010', 'Equity Real Estate Investment Trusts (REITs)', '6010', 'Real Estate', '60', 'Real Estate'),
    ('60101030', 'Hotel & Resort REITs', 'Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of hotel and resort properties.', '601010', 'Equity Real Estate Investment Trusts (REITs)', '6010', 'Real Estate', '60', 'Real Estate'),
    ('60101040', 'Office REITs', 'Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of office properties.', '601010', 'Equity Real Estate Investment Trusts (REITs)', '6010', 'Real Estate', '60', 'Real Estate'),
    ('60101050', 'Health Care REITs', 'Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of properties serving the health care industry, including hospitals, nursing homes, and assisted living properties.', '601010', 'Equity Real Estate Investment Trusts (REITs)', '6010', 'Real Estate', '60', 'Real Estate'),
    ('60101060', 'Residential REITs', 'Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of residential properties including multifamily homes, apartments, manufactured homes and student housing properties', '601010', 'Equity Real Estate Investment Trusts (REITs)', '6010', 'Real Estate', '60', 'Real Estate'),
    ('60101070', 'Retail REITs', 'Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of shopping malls, outlet malls, neighborhood and community shopping centers.', '601010', 'Equity Real Estate Investment Trusts (REITs)', '6010', 'Real Estate', '60', 'Real Estate'),
    ('60101080', 'Specialized REITs', 'Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of properties not classified elsewhere. Includes trusts that operate and invest in storage properties. It also includes REITs that do not generate a majority of their revenues and income from real estate rental and leasing operations.', '601010', 'Equity Real Estate Investment Trusts (REITs)', '6010', 'Real Estate', '60', 'Real Estate'),
    ('60102010', 'Diversified Real Estate Activities', 'Companies engaged in a diverse spectrum of real estate activities including real estate development & sales, real estate management, or real estate services, but with no dominant business line.', '601020', 'Real Estate Management & Development', '6010', 'Real Estate', '60', 'Real Estate'),
    ('60102020', 'Real Estate Operating Companies', 'Companies engaged in operating real estate properties for the purpose of leasing & management.', '601020', 'Real Estate Management & Development', '6010', 'Real Estate', '60', 'Real Estate'),
    ('60102030', 'Real Estate Development', 'Companies that develop real estate and sell the properties after development. Excludes companies classified in the Homebuilding Sub-Industry.', '601020', 'Real Estate Management & Development', '6010', 'Real Estate', '60', 'Real Estate'),
    ('60102040', 'Real Estate Services', 'Real estate service providers such as real estate agents, brokers & real estate appraisers.', '601020', 'Real Estate Management & Development', '6010', 'Real Estate', '60', 'Real Estate');

-- ISO 3166-1 countries from docs/references/master-data/iso-country-codes, names verbatim.
INSERT INTO ref_country (alpha2, name) VALUES
    ('AF', 'Afghanistan'),
    ('AX', 'Åland Islands'),
    ('AL', 'Albania'),
    ('DZ', 'Algeria'),
    ('AS', 'American Samoa'),
    ('AD', 'Andorra'),
    ('AO', 'Angola'),
    ('AI', 'Anguilla'),
    ('AQ', 'Antarctica'),
    ('AG', 'Antigua and Barbuda'),
    ('AR', 'Argentina'),
    ('AM', 'Armenia'),
    ('AW', 'Aruba'),
    ('AU', 'Australia'),
    ('AT', 'Austria'),
    ('AZ', 'Azerbaijan'),
    ('BS', 'Bahamas (The)'),
    ('BH', 'Bahrain'),
    ('BD', 'Bangladesh'),
    ('BB', 'Barbados'),
    ('BY', 'Belarus'),
    ('BE', 'Belgium'),
    ('BZ', 'Belize'),
    ('BJ', 'Benin'),
    ('BM', 'Bermuda'),
    ('BT', 'Bhutan'),
    ('BO', 'Bolivia (Plurinational State of)'),
    ('BQ', 'Bonaire, Sint Eustatius and Saba'),
    ('BA', 'Bosnia and Herzegovina'),
    ('BW', 'Botswana'),
    ('BV', 'Bouvet Island'),
    ('BR', 'Brazil'),
    ('IO', 'British Indian Ocean Territory (the)'),
    ('BN', 'Brunei Darussalam'),
    ('BG', 'Bulgaria'),
    ('BF', 'Burkina Faso'),
    ('BI', 'Burundi'),
    ('CV', 'Cabo Verde'),
    ('KH', 'Cambodia'),
    ('CM', 'Cameroon'),
    ('CA', 'Canada'),
    ('KY', 'Cayman Islands (the)'),
    ('CF', 'Central African Republic (the)'),
    ('TD', 'Chad'),
    ('CL', 'Chile'),
    ('CN', 'China'),
    ('CX', 'Christmas Island'),
    ('CC', 'Cocos (Keeling) Islands (the)'),
    ('CO', 'Colombia'),
    ('KM', 'Comoros (the)'),
    ('CD', 'Congo (the Democratic Republic of the)'),
    ('CG', 'Congo (the)'),
    ('CK', 'Cook Islands (the)'),
    ('CR', 'Costa Rica'),
    ('CI', 'Côte d''Ivoire'),
    ('HR', 'Croatia'),
    ('CU', 'Cuba'),
    ('CW', 'Curaçao'),
    ('CY', 'Cyprus'),
    ('CZ', 'Czechia'),
    ('DK', 'Denmark'),
    ('DJ', 'Djibouti'),
    ('DM', 'Dominica'),
    ('DO', 'Dominican Republic (the)'),
    ('EC', 'Ecuador'),
    ('EG', 'Egypt'),
    ('SV', 'El Salvador'),
    ('GQ', 'Equatorial Guinea'),
    ('ER', 'Eritrea'),
    ('EE', 'Estonia'),
    ('SZ', 'Eswatini'),
    ('ET', 'Ethiopia'),
    ('FK', 'Falkland Islands (the) [Malvinas]'),
    ('FO', 'Faroe Islands (the)'),
    ('FJ', 'Fiji'),
    ('FI', 'Finland'),
    ('FR', 'France'),
    ('GF', 'French Guiana'),
    ('PF', 'French Polynesia'),
    ('TF', 'French Southern Territories (the)'),
    ('GA', 'Gabon'),
    ('GM', 'Gambia (the)'),
    ('GE', 'Georgia'),
    ('DE', 'Germany'),
    ('GH', 'Ghana'),
    ('GI', 'Gibraltar'),
    ('GR', 'Greece'),
    ('GL', 'Greenland'),
    ('GD', 'Grenada'),
    ('GP', 'Guadeloupe'),
    ('GU', 'Guam'),
    ('GT', 'Guatemala'),
    ('GG', 'Guernsey'),
    ('GN', 'Guinea'),
    ('GW', 'Guinea-Bissau'),
    ('GY', 'Guyana'),
    ('HT', 'Haiti'),
    ('HM', 'Heard Island and McDonald Islands'),
    ('VA', 'Holy See (the)'),
    ('HN', 'Honduras'),
    ('HK', 'Hong Kong'),
    ('HU', 'Hungary'),
    ('IS', 'Iceland'),
    ('IN', 'India'),
    ('ID', 'Indonesia'),
    ('IR', 'Iran (Islamic Republic of)'),
    ('IQ', 'Iraq'),
    ('IE', 'Ireland'),
    ('IM', 'Isle of Man'),
    ('IL', 'Israel'),
    ('IT', 'Italy'),
    ('JM', 'Jamaica'),
    ('JP', 'Japan'),
    ('JE', 'Jersey'),
    ('JO', 'Jordan'),
    ('KZ', 'Kazakhstan'),
    ('KE', 'Kenya'),
    ('KI', 'Kiribati'),
    ('KP', 'Korea (the Democratic People''s Republic of)'),
    ('KR', 'Korea (the Republic of)'),
    ('KW', 'Kuwait'),
    ('KG', 'Kyrgyzstan'),
    ('LA', 'Lao People''s Democratic Republic (the)'),
    ('LV', 'Latvia'),
    ('LB', 'Lebanon'),
    ('LS', 'Lesotho'),
    ('LR', 'Liberia'),
    ('LY', 'Libya'),
    ('LI', 'Liechtenstein'),
    ('LT', 'Lithuania'),
    ('LU', 'Luxembourg'),
    ('MO', 'Macao'),
    ('MG', 'Madagascar'),
    ('MW', 'Malawi'),
    ('MY', 'Malaysia'),
    ('MV', 'Maldives'),
    ('ML', 'Mali'),
    ('MT', 'Malta'),
    ('MH', 'Marshall Islands (the)'),
    ('MQ', 'Martinique'),
    ('MR', 'Mauritania'),
    ('MU', 'Mauritius'),
    ('YT', 'Mayotte'),
    ('MX', 'Mexico'),
    ('FM', 'Micronesia (Federated States of)'),
    ('MD', 'Moldova (the Republic of)'),
    ('MC', 'Monaco'),
    ('MN', 'Mongolia'),
    ('ME', 'Montenegro'),
    ('MS', 'Montserrat'),
    ('MA', 'Morocco'),
    ('MZ', 'Mozambique'),
    ('MM', 'Myanmar'),
    ('NA', 'Namibia'),
    ('NR', 'Naoero'),
    ('NP', 'Nepal'),
    ('NL', 'Netherlands (Kingdom of the)'),
    ('NC', 'New Caledonia'),
    ('NZ', 'New Zealand'),
    ('NI', 'Nicaragua'),
    ('NE', 'Niger (the)'),
    ('NG', 'Nigeria'),
    ('NU', 'Niue'),
    ('NF', 'Norfolk Island'),
    ('MK', 'North Macedonia'),
    ('MP', 'Northern Mariana Islands (the)'),
    ('NO', 'Norway'),
    ('OM', 'Oman'),
    ('PK', 'Pakistan'),
    ('PW', 'Palau'),
    ('PS', 'Palestine, State of'),
    ('PA', 'Panama'),
    ('PG', 'Papua New Guinea'),
    ('PY', 'Paraguay'),
    ('PE', 'Peru'),
    ('PH', 'Philippines (the)'),
    ('PN', 'Pitcairn'),
    ('PL', 'Poland'),
    ('PT', 'Portugal'),
    ('PR', 'Puerto Rico'),
    ('QA', 'Qatar'),
    ('RE', 'Réunion'),
    ('RO', 'Romania'),
    ('RU', 'Russian Federation (the)'),
    ('RW', 'Rwanda'),
    ('BL', 'Saint Barthélemy'),
    ('SH', 'Saint Helena, Ascension and Tristan da Cunha'),
    ('KN', 'Saint Kitts and Nevis'),
    ('LC', 'Saint Lucia'),
    ('MF', 'Saint Martin (French part)'),
    ('PM', 'Saint Pierre and Miquelon'),
    ('VC', 'Saint Vincent and the Grenadines'),
    ('WS', 'Samoa'),
    ('SM', 'San Marino'),
    ('ST', 'Sao Tome and Principe'),
    ('SA', 'Saudi Arabia'),
    ('SN', 'Senegal'),
    ('RS', 'Serbia'),
    ('SC', 'Seychelles'),
    ('SL', 'Sierra Leone'),
    ('SG', 'Singapore'),
    ('SX', 'Sint Maarten (Dutch part)'),
    ('SK', 'Slovakia'),
    ('SI', 'Slovenia'),
    ('SB', 'Solomon Islands'),
    ('SO', 'Somalia'),
    ('ZA', 'South Africa'),
    ('GS', 'South Georgia and the South Sandwich Islands'),
    ('SS', 'South Sudan'),
    ('ES', 'Spain'),
    ('LK', 'Sri Lanka'),
    ('SD', 'Sudan (the)'),
    ('SR', 'Suriname'),
    ('SJ', 'Svalbard and Jan Mayen'),
    ('SE', 'Sweden'),
    ('CH', 'Switzerland'),
    ('SY', 'Syrian Arab Republic (the)'),
    ('TW', 'Taiwan (Province of China)'),
    ('TJ', 'Tajikistan'),
    ('TZ', 'Tanzania, the United Republic of'),
    ('TH', 'Thailand'),
    ('TL', 'Timor-Leste'),
    ('TG', 'Togo'),
    ('TK', 'Tokelau'),
    ('TO', 'Tonga'),
    ('TT', 'Trinidad and Tobago'),
    ('TN', 'Tunisia'),
    ('TR', 'Türkiye'),
    ('TM', 'Turkmenistan'),
    ('TC', 'Turks and Caicos Islands (the)'),
    ('TV', 'Tuvalu'),
    ('UG', 'Uganda'),
    ('UA', 'Ukraine'),
    ('AE', 'United Arab Emirates (the)'),
    ('GB', 'United Kingdom of Great Britain and Northern Ireland (the)'),
    ('UM', 'United States Minor Outlying Islands (the)'),
    ('US', 'United States of America (the)'),
    ('UY', 'Uruguay'),
    ('UZ', 'Uzbekistan'),
    ('VU', 'Vanuatu'),
    ('VE', 'Venezuela (Bolivarian Republic of)'),
    ('VN', 'Viet Nam'),
    ('VG', 'Virgin Islands (British)'),
    ('VI', 'Virgin Islands (U.S.)'),
    ('WF', 'Wallis and Futuna'),
    ('EH', 'Western Sahara*'),
    ('YE', 'Yemen'),
    ('ZM', 'Zambia'),
    ('ZW', 'Zimbabwe');

-- ISDA Taxonomy v2.0, equity sheet ('Equity Full') from docs/references/master-data/product-classification-isda:
-- one row per base product, sub-product and transaction type. The industry sector column is a placeholder and not loaded.
INSERT INTO ref_isda_equity_taxonomy (isda_row_no, base_product, sub_product, transaction_type) VALUES
    (1, 'Swap', 'Price Return Basic Performance', 'Single Name'),
    (2, 'Swap', 'Price Return Basic Performance', 'Single Index'),
    (3, 'Swap', 'Price Return Basic Performance', 'Basket'),
    (4, 'Swap', 'Parameter Return Dividend', 'Single Name'),
    (5, 'Swap', 'Parameter Return Dividend', 'Single Index'),
    (6, 'Swap', 'Parameter Return Dividend', 'Basket'),
    (7, 'Swap', 'Parameter Return Variance', 'Single Name'),
    (8, 'Swap', 'Parameter Return Variance', 'Single Index'),
    (9, 'Swap', 'Parameter Return Variance', 'Basket'),
    (10, 'Swap', 'Parameter Return Volatility', 'Single Name'),
    (11, 'Swap', 'Parameter Return Volatility', 'Single Index'),
    (12, 'Swap', 'Parameter Return Volatility', 'Basket'),
    (13, 'Portfolio Swap', 'Price Return Basic Performance', 'Single Name'),
    (14, 'Portfolio Swap', 'Price Return Basic Performance', 'Single Index'),
    (15, 'Portfolio Swap', 'Price Return Basic Performance', 'Basket'),
    (16, 'Contract For Difference', 'Price Return Basic Performance', 'Single Name'),
    (17, 'Contract For Difference', 'Price Return Basic Performance', 'Single Index'),
    (18, 'Contract For Difference', 'Price Return Basic Performance', 'Basket'),
    (19, 'Option', 'Price Return Basic Performance', 'Single Name'),
    (20, 'Option', 'Price Return Basic Performance', 'Single Index'),
    (21, 'Option', 'Price Return Basic Performance', 'Basket'),
    (22, 'Option', 'Parameter Return Dividend', 'Single Name'),
    (23, 'Option', 'Parameter Return Dividend', 'Single Index'),
    (24, 'Option', 'Parameter Return Dividend', 'Basket'),
    (25, 'Option', 'Parameter Return Variance', 'Single Name'),
    (26, 'Option', 'Parameter Return Variance', 'Single Index'),
    (27, 'Option', 'Parameter Return Variance', 'Basket'),
    (28, 'Option', 'Parameter Return Volatility', 'Single Name'),
    (29, 'Option', 'Parameter Return Volatility', 'Single Index'),
    (30, 'Option', 'Parameter Return Volatility', 'Basket'),
    (31, 'Forward', 'Price Return Basic Performance', 'Single Name'),
    (32, 'Forward', 'Price Return Basic Performance', 'Single Index'),
    (33, 'Forward', 'Price Return Basic Performance', 'Basket'),
    (34, 'Other', NULL, NULL);
